name: limosat
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - shapely
  - pyproj
  - rasterio
  - opencv
  - pytorch
  - kornia
  - pyyaml
  - pytest
  - pip:
      - -e .
