name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11.3
          activate-environment: limosat
          environment-file: environment.yaml
    
      - name: Add 'defaults' channel explicitly
        run: conda config --add channels defaults

      - name: Add repo directory to PYTHONPATH
        shell: bash -l {0}
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest tests/tests.py -v